apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-exercise
  namespace: argocd

spec:

  project: devops-exercise

  source:
    repoURL: https://github.com/duanegbrown3/senior-devops-exercise.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true