name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:

  terraform:
    uses: ./.github/workflows/terraform.yml

  docker:
    needs: terraform
    uses: ./.github/workflows/docker.yml

  security:
    needs: docker
    uses: ./.github/workflows/security.yml